### ISSUE TITLE
feature request: attach custom tags to the ec2

### ISSUE THREAD

**Issue by pharindoko** [CloudSnorkel/cdk-github-runners#524] opened 2024-03-17 09:38 UTC
Hey @kichik,

I need the possiblity to attach custom labels to an ec2.
Background: I want to be able to track the costs in cost explorer based on certain labels.

1. I imagine to have an optional step in the stepfunction in between to match labels for certain runners based on the data provided.
   Basically a lambda that I can provide to return back labels in a certain format.
2. These labels will be attached additionally to the new created ec2.

br,

@pharindoko

**Comment by kichik** [comment] 2024-03-17 11:50
Do you mean tags?

**Comment by pharindoko** [comment] 2024-03-17 13:00
> Do you mean tags?

Yes I mean tags btw 😄

**Comment by kichik** [comment] 2024-03-17 18:38
I believe it should already be copying the provider tags to the EC2 instance. So you should be able to use `cdk.Tags.of(provider).add('tagName', 'tagValue')`. Does that not work? Or do you need it even more dynamic than that?

**Comment by pharindoko** [comment] 2024-03-17 19:34
> I believe it should already be copying the provider tags to the EC2 instance. So you should be able to use `cdk.Tags.of(provider).add('tagName', 'tagValue')`. Does that not work? Or do you need it even more dynamic than that?

I would need it more dynamic.
Having a lambda function or some typescript function in between, that I can overwrite, would be nice.
I need to do some mapping and match values.

**Comment by kichik** [comment] 2024-03-17 19:57
What data would this Lambda need? Requested labels? The entire webhook?

**Comment by pharindoko** [comment] 2024-03-17 20:41
> What data would this Lambda need? Requested labels? The entire webhook?

The entire webhook to get things like org, repo, job run, step and the labels.

**Comment by kichik** [comment] 2024-03-17 21:45
I'll have to think about the best way to enable such a feature request.

For now you can use the environment variables already supplied by the actions runner code. `GITHUB_REPOSITORY`, `GITHUB_RUN_ID`, etc. are already there. Check out the [integration test](https://github.com/CloudSnorkel/cdk-github-runners/actions/runs/7514403199/job/20457235387). It runs `export` to show them all. You can then give your instances permission to [tag themselves](https://stackoverflow.com/a/54870258/492773). If you want to be real fancy, you can have a [runner hook](https://github.com/actions/runner/blob/main/docs/adrs/1751-runner-job-hooks.md) automatically take care of it. One of the [discussion threads](https://github.com/CloudSnorkel/cdk-github-runners/discussions/509) has a usage example.

**Comment by pharindoko** [comment] 2024-03-17 22:53
Will do.
Thanks for the hinz @kichik.

**Comment by pharindoko** [comment] 2024-04-03 21:18
> I'll have to think about the best way to enable such a feature request.
> 
> 
> 
> For now you can use the environment variables already supplied by the actions runner code. `GITHUB_REPOSITORY`, `GITHUB_RUN_ID`, etc. are already there. Check out the [integration test](https://github.com/CloudSnorkel/cdk-github-runners/actions/runs/7514403199/job/20457235387). It runs `export` to show them all. You can then give your instances permission to [tag themselves](https://stackoverflow.com/a/54870258/492773). If you want to be real fancy, you can have a [runner hook](https://github.com/actions/runner/blob/main/docs/adrs/1751-runner-job-hooks.md) automatically take care of it. One of the [discussion threads](https://github.com/CloudSnorkel/cdk-github-runners/discussions/509) has a usage example.


I had some time to really understand the solution you propose. Yes this definitely will work but I fear that this could be heard to debug, monitor and to modify.

Could it be another option to provide some kind of pre-deployment step in the stepfunction that can be overwritten to select and add tags that can be attached e.g. to the ec2 or other components ?

**Comment by kichik** [comment] 2024-04-05 14:55
I still don't have a good idea of what something like that would look like. For example, one of the big problems is that it can't be generic. Settings tags is only supported natively on EC2 and through some hacks on ECS ([RunTask](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RunTask.html#API_RunTask_RequestSyntax) doesn't have an option for tags).

Maybe some sort of an escape hatch is in place. Even that I'm not sure how to do elegantly as task objects don't have any option to override until they're rendered and then you have to deal with the entire step function JSON. We would have to take out all of the parameters into an object, pass it to a custom lambda, and then use the results as input for the actual step. But then when this is not used, we just skip the pass and directly pass the parameters?

**Comment by pharindoko** [comment] 2024-04-06 23:19
> I still don't have a good idea of what something like that would look like. For example, one of the big problems is that it can't be generic. Settings tags is only supported natively on EC2 and through some hacks on ECS ([RunTask](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RunTask.html#API_RunTask_RequestSyntax) doesn't have an option for tags).
> 
> Maybe some sort of an escape hatch is in place. Even that I'm not sure how to do elegantly as task objects don't have any option to override until they're rendered and then you have to deal with the entire step function JSON. We would have to take out all of the parameters into an object, pass it to a custom lambda, and then use the results as input for the actual step. But then when this is not used, we just skip the pass and directly pass the parameters?

Hmm got it. Yes so to do it in a generic manner doesn`t make sense.
But to do it specifically for the ec2 provider could be an option.
e.g. here:
https://github.com/CloudSnorkel/cdk-github-runners/blob/f64d5a4c0f23abbe98cfc4dc6532c107b33d56f6/src/providers/ec2.ts#L415
In case `customTags` option is set to true, an additional step function task will be created (input: the params object above) - The lambda for the step function in that case has to be provided by the user.
- The output will be attached as tags to the instance

**Comment by kichik** [comment] 2024-04-11 13:31
It just occurred to me that assigning the tags before a job is assigned to the runner may result in unexpected results. Especially if you're using organization level registration. There is no guarantee the runner will pick up the job you think it will if the labels are shared. 

If the labels are not shared, each provider can use its own static tags. This won't work right now as the tags come from the launch template which is generated by the image builder. I think that part might be resolved by fleets (#518). My current plan is to move EC2 provider to using fleets with SSM document. It would require the provider to create its own launch template. Once it's the provider creating the launch template, using `cdk.Tags.of(provider).add(...)` would work as expected.

I still can't get behind a function specifically for tags specifically for EC2 provider. If we could think of a way to make a generic escape hatch where you have a way to edit the step function after being generated, I think that would make more sense. You can technically already do it by overriding the entire JSON. But that's not a realistic method as you'd have to recreate everything.

**Comment by pharindoko** [comment] 2024-04-18 19:55
I haven`t thought about this - but auto tagging should help me ... https://medium.com/@mithun.kadyada/lambda-function-for-auto-tagging-ec2-instances-cff38c30bdc8

One thing to mention:
it would be nice if you could add organization and repository statically to each ec2 machine created by the ec2-provider. Is this possible ? @kichik

**Comment by kichik** [comment] 2024-04-19 17:02
How would the auto-tagging Lambda have access to the webhook info needed to properly tag the instance?

> it would be nice if you could add organization and repository statically to each ec2 machine created by the ec2-provider. Is this possible ?

Not sure what you mean by that. Are you asking to have access to the repository or organization where the instance was registered? As in some tag that the Lambda function could later read?

**Comment by pharindoko** [comment] 2024-04-20 00:18
> How would the auto-tagging Lambda have access to the webhook info needed to properly tag the instance?
> 
> 
> 
> > it would be nice if you could add organization and repository statically to each ec2 machine created by the ec2-provider. Is this possible ?
> 
> 
> 
> Not sure what you mean by that. Are you asking to have access to the repository or organization where the instance was registered? As in some tag that the Lambda function could later read?


Yes I would like to have a simple way to read out the relation between the runner and the github org + repo when the runner is started.

**Comment by kichik** [comment] 2024-04-24 13:59
Might this information be available in the state machine [log](https://github.com/CloudSnorkel/cdk-github-runners/pull/150)?

**Comment by pharindoko** [comment] 2024-05-27 15:19
Hey @kichik,

I would like to get more overview about the costs.
it would be still nice to have the tags for owner + repo or set all of the params as tags. Attaching tags directly is the easiest way.
I understand that not all providers support tags, but it would be nice if we can activate it at least for ec2s.
Query the logs and attach the tags seems to me like a workaround.

The params are already there:
https://github.com/CloudSnorkel/cdk-github-runners/blob/f0aebce56e38e7e7c37603db2313a2f0b61483a7/src/providers/ec2.ts#L407

Would be great to append them here:
https://github.com/CloudSnorkel/cdk-github-runners/blob/f0aebce56e38e7e7c37603db2313a2f0b61483a7/src/providers/ec2.ts#L447

```
  TagSpecifications: [ 
    { 
      ResourceType: "instance",
      Tags: [ // TagList
        { // Tag
          Key: "STRING_VALUE",
          Value: "STRING_VALUE",
        },
      ],
    },
  ],```

I could create a PR and test it. 
Will I have your support ?

**Comment by kichik** [comment] 2024-05-29 13:31
Turns out all resources do support tags. So we should be able to tag with the provider construct path and its labels. The problem is AWS tags don't allow commas. Runner labels [don't seem to have any restrictions besides commas](https://github.com/actions/runner/blob/ce4d7be00f4834b6889a82ea55020bb15fa834bf/src/Runner.Listener/Configuration/Validators.cs#L50-L63), so I'm not sure what's the best solution for that would be.

As for tagging with the owner and repo, I still don't see how we can do that in a generic and/or non-clunky way. We can't trust what the step function registers it as because of organization level registration. Adding a separate Lambda to query it from GitHub once the runner is assigned sounds as clunky as reading the log. And it will have limited provider support. At that point I would still prefer the self-tagging route.

**Comment by kichik** [comment] 2024-05-29 23:56
Would #582 help? Would it be enough?

**Comment by pharindoko** [comment] 2024-05-30 07:16
> Turns out all resources do support tags at deploy time. So we should be able to tag with the provider construct path and its labels. The problem is AWS tags don't allow commas. Runner labels [don't seem to have any restrictions besides commas](https://github.com/actions/runner/blob/ce4d7be00f4834b6889a82ea55020bb15fa834bf/src/Runner.Listener/Configuration/Validators.cs#L50-L63), so I'm not sure what's the best solution for that would be.
> 
> 
> 
> As for tagging with the owner and repo, I still don't see how we can do that in a generic and/or non-clunky way. We can't trust what the step function registers it as because of organization level registration. Adding a separate Lambda to query it from GitHub once the runner is assigned sounds as clunky as reading the log. And it will have limited provider support. At that point I would still prefer the self-tagging route.

Thanks that you took the time to write. You're right. In this case I would even prefer a query to Github once the runner is assigned or as you mentioned self-tag the instance. There was a hook available right ? Would mean I could add some custom shell script to self-tag.

**Comment by pharindoko** [comment] 2024-05-30 07:17
> Would #582 help? Would it be enough?

This was basically what I meant but I would need more information. :) and you already delivered the reason why it's a bad idea.

**Comment by pharindoko** [comment] 2024-05-30 11:02
I guess I would try the github way first. It's easy to change it as stepfunction.
Can you at least add the organization tag to the instance ?

**Comment by kichik** [comment] 2024-05-30 13:46
> In this case I would even prefer a query to Github once the runner is assigned or as you mentioned self-tag the instance. There was a hook available right ? Would mean I could add some custom shell script to self-tag.

Yeah. The image builder will set `ACTIONS_RUNNER_HOOK_JOB_STARTED` pointing to a script that it adds. The script will self-tag.

> Can you at least add the organization tag to the instance in https://github.com/CloudSnorkel/cdk-github-runners/pull/582 ?

Sadly, no. Organization is not available during deployment time. We don't know which app/organization/repository/etc. will register with the orchestrator after it's deployed.

**Comment by pharindoko** [comment] 2024-05-31 07:45
#583

**Comment by pharindoko** [comment] 2024-05-31 08:37
I would have a generic proposal:

Regarding the hook script solution: (https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/running-scripts-before-or-after-a-job)

A basic script `runner-started.sh` or `runner-started.ps1` is created for linux/windows when a new image will be built with imagebuidler.

This script will be referenced at provider startup when the runner configuration will be done e.g. for linux
`export ACTIONS_RUNNER_HOOK_JOB_STARTED="/opt/runner/runner-started.sh"` 

If somebody wants to overwrite this it can be done using a custom `addComponent` function of the builder.

```
builder.addComponent(
  RunnerImageComponent.custom({
    name: 'Overwrite started-runner.sh',
    commands: [
      'set -ex',
      'echo "..." > /opt/runner/runner-started.sh',
    ],
  }),
);
```

**Comment by kichik** [comment] 2024-05-31 23:53
You should already be able to do it. The following worked for me.

```typescript
const builder = Ec2RunnerProvider.imageBuilder(stack, 'builder');
builder.addComponent(
  RunnerImageComponent.environmentVariables({
    ACTIONS_RUNNER_HOOK_JOB_STARTED: '/home/runner/runner-started.sh',
  }),
);
builder.addComponent(
  RunnerImageComponent.custom({
    name: 'Self-tag',
    commands: [
      'echo "#!/bin/bash" > /home/runner/runner-started.sh',
      'echo \'TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 60")\' >> /home/runner/runner-started.sh',
      'echo \'INSTANCE_ID=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/instance-id)\' >> /home/runner/runner-started.sh',
      'echo \'aws ec2 create-tags --resources "$INSTANCE_ID" --tags Key=owner,Value=$GITHUB_REPOSITORY_OWNER Key=repository,Value=$GITHUB_REPOSITORY\' >> /home/runner/runner-started.sh',
      'chmod +x /home/runner/runner-started.sh',
    ],
  }),
);

const provider = new Ec2RunnerProvider(stack, 'EC2', {
  labels: ['self-tag-provider'],
  imageBuilder: builder,
});
provider.grantPrincipal.addToPrincipalPolicy(new iam.PolicyStatement({
  actions: ['ec2:CreateTags'],
  resources: ['*'],
  conditions: {
    StringEquals: {
      'aws:Resource': 'instance/${ec2:InstanceID}',
    },
  },
}));
```

**Comment by pharindoko** [comment] 2024-06-02 12:16
I'll try it out and will close it for now

**Closed** 2024-06-02 12:17 UTC
